### ISSUE TITLE
QOL: throw error on invalid backend parameter

### ISSUE THREAD

**Issue by KonradHoeffner** [belayeng/quadstore#140]
I made the mistake of using `backend:memdown` instead of `backend:memdown()`in the constructor of Quadstore:

```
...
import memdown from "memdown";
const store = new Quadstore({ backend:memdown, comunica: newEngine(), dataFactory: DataFactory});
...
await store.open();
```

However this only throws an error when calling `store.open`:
```
throw new Error(`Store is not ready (status: "${this.db.status}"). Did you call store.open()?`);
                  ^
Error: Store is not ready (status: "undefined"). Did you call store.open()?
```

And the error message does not point out that the db is in the wrong format. It would be helpful if the constructor would throw an error that the backend is invalid.

**Comment by KonradHoeffner** [comment]
I'm unfortunately not familiar enough with the codebase to create a PR but I shared our use case in #112, thanks!

**Comment by jacoscaz** [comment]
Done, will be included in the next version.
